export const mockedManagerId = 'Manager'
export const mockedManagerName = 'John Doe'
export const mockedManagerEmail = 'johndoe@example.com'
export const mockedManagerPhone = '99999999999'
export const mockedRestaurantId = 'ckv1q5e2q00013f66hsg0bbzf'
export const mockedRestaurantName = 'Pizza do John'
export const mockedRestaurantDescription = 'Custom restaurant description'
export const mockErrorOrderId = 'ciu0c0l6y0000jx6m6brb8l9m'
